name: app
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  dio: ^5.7.0
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  font_awesome_flutter: ^10.7.0
  get_it: ^8.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.9.0
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  smooth_page_indicator: ^1.2.0+3

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/json/
    - assets/map_style.json

  fonts:
    - family: Peter
      fonts:
        - asset: assets/fonts/Peter-regular.otf
        - asset: assets/fonts/Peter-black.otf
          weight: 700
    - family: Laila
      fonts:
        - asset: assets/fonts/Laila-Medium.ttf
        - asset: assets/fonts/Laila-Regular.ttf
          weight: 700

    - family: Work_Sans
      fonts:
        - asset: assets/fonts/WorkSans-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/WorkSans-Light.ttf
          weight: 300
        - asset: assets/fonts/WorkSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/WorkSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/WorkSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/WorkSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/WorkSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/WorkSans-Black.ttf
          weight: 900
